"""supplement_items, supplement_schedules, medication_items, medication_schedules수정

Revision ID: 019dc14c09e9
Revises: 7455082168ff
Create Date: 2026-07-22 16:20:05.619932

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "019dc14c09e9"
down_revision: Union[str, Sequence[str], None] = "7455082168ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "supplement_items",
        "supplement_item_seq",
        existing_type=mysql.INTEGER(),
        comment="영양제 기본키",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "supplement_items",
        "name",
        existing_type=mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=50),
        comment="명칭(이름)",
        existing_nullable=False,
    )
    op.alter_column(
        "supplement_items",
        "product_name",
        existing_type=mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=50),
        comment="제품명",
        existing_nullable=True,
    )
    op.alter_column(
        "supplement_items",
        "company_name",
        existing_type=mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=50),
        comment="회사명",
        existing_nullable=True,
    )
    op.alter_column(
        "supplement_items",
        "nutrition_info",
        existing_type=mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=500),
        comment="함량/영양정보",
        existing_nullable=True,
    )
    op.alter_column(
        "supplement_items",
        "description",
        existing_type=mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=500),
        comment="설명",
        existing_nullable=True,
    )
    op.alter_column(
        "supplement_items",
        "photo_path",
        existing_type=mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=255),
        comment="사진 경로",
        existing_nullable=True,
    )
    op.alter_column(
        "supplement_items",
        "timing",
        existing_type=mysql.ENUM(
            "EMPTY",
            "BEFORE",
            "AFTER",
            charset="utf8mb4",
            collation="utf8mb4_unicode_ci",
        ),
        comment="복용 시기",
        existing_nullable=False,
    )
    op.alter_column(
        "supplement_items",
        "status",
        existing_type=mysql.ENUM("ING", "PAUSE", "END", charset="utf8mb4", collation="utf8mb4_unicode_ci"),
        comment="복용 상태",
        existing_nullable=False,
    )
    op.alter_column(
        "supplement_items",
        "created_at",
        existing_type=mysql.DATETIME(),
        comment="만들어진 날짜",
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "supplement_items",
        "created_at",
        existing_type=mysql.DATETIME(),
        comment=None,
        existing_comment="만들어진 날짜",
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "supplement_items",
        "status",
        existing_type=mysql.ENUM("ING", "PAUSE", "END", charset="utf8mb4", collation="utf8mb4_unicode_ci"),
        comment=None,
        existing_comment="복용 상태",
        existing_nullable=False,
    )
    op.alter_column(
        "supplement_items",
        "timing",
        existing_type=mysql.ENUM(
            "EMPTY",
            "BEFORE",
            "AFTER",
            charset="utf8mb4",
            collation="utf8mb4_unicode_ci",
        ),
        comment=None,
        existing_comment="복용 시기",
        existing_nullable=False,
    )
    op.alter_column(
        "supplement_items",
        "photo_path",
        existing_type=mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=255),
        comment=None,
        existing_comment="사진 경로",
        existing_nullable=True,
    )
    op.alter_column(
        "supplement_items",
        "description",
        existing_type=mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=500),
        comment=None,
        existing_comment="설명",
        existing_nullable=True,
    )
    op.alter_column(
        "supplement_items",
        "nutrition_info",
        existing_type=mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=500),
        comment=None,
        existing_comment="함량/영양정보",
        existing_nullable=True,
    )
    op.alter_column(
        "supplement_items",
        "company_name",
        existing_type=mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=50),
        comment=None,
        existing_comment="회사명",
        existing_nullable=True,
    )
    op.alter_column(
        "supplement_items",
        "product_name",
        existing_type=mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=50),
        comment=None,
        existing_comment="제품명",
        existing_nullable=True,
    )
    op.alter_column(
        "supplement_items",
        "name",
        existing_type=mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=50),
        comment=None,
        existing_comment="명칭(이름)",
        existing_nullable=False,
    )
    op.alter_column(
        "supplement_items",
        "supplement_item_seq",
        existing_type=mysql.INTEGER(),
        comment=None,
        existing_comment="영양제 기본키",
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
