"""blood_pressure_records, blood_sugar_records 생성

Revision ID: 086fffd17feb
Revises: 1f2cf4aba307
Create Date: 2026-07-22 17:42:38.532046

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "086fffd17feb"
down_revision: Union[str, Sequence[str], None] = "1f2cf4aba307"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blood_pressure_records",
        sa.Column(
            "blood_pressure_record_seq", sa.Integer(), autoincrement=True, nullable=False, comment="혈압 기록 기본키"
        ),
        sa.Column("user_seq", sa.Integer(), nullable=False, comment="유저 기본키(외래키)"),
        sa.Column("measured_at", sa.DateTime(), nullable=False, comment="측정 일시"),
        sa.Column("systolic", sa.Integer(), nullable=False, comment="수축기"),
        sa.Column("diastolic", sa.Integer(), nullable=False, comment="이완기"),
        sa.Column("pulse", sa.Integer(), nullable=False, comment="맥박수"),
        sa.Column("memo", sa.String(length=500), nullable=True, comment="비고"),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="만들어진 날짜"
        ),
        sa.ForeignKeyConstraint(
            ["user_seq"],
            ["users.user_seq"],
        ),
        sa.PrimaryKeyConstraint("blood_pressure_record_seq"),
    )
    op.create_table(
        "blood_sugar_records",
        sa.Column(
            "blood_sugar_record_seq", sa.Integer(), autoincrement=True, nullable=False, comment="혈당 기록 기본키"
        ),
        sa.Column("user_seq", sa.Integer(), nullable=False, comment="유저 기본키(외래키)"),
        sa.Column("measured_at", sa.DateTime(), nullable=False, comment="측정 일시"),
        sa.Column(
            "check_timing", sa.Enum("EMPTY", "AFTER_2H", name="checktiming"), nullable=False, comment="측정 시기"
        ),
        sa.Column("glucose_value", sa.Integer(), nullable=False, comment="혈당 수치"),
        sa.Column("memo", sa.String(length=500), nullable=True, comment="비고"),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="만들어진 날짜"
        ),
        sa.ForeignKeyConstraint(
            ["user_seq"],
            ["users.user_seq"],
        ),
        sa.PrimaryKeyConstraint("blood_sugar_record_seq"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blood_sugar_records")
    op.drop_table("blood_pressure_records")
    # ### end Alembic commands ###
