"""supplement_logs, medication_logs 생성

Revision ID: 1f2cf4aba307
Revises: bd514ccfd36d
Create Date: 2026-07-22 16:52:57.815583

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f2cf4aba307"
down_revision: Union[str, Sequence[str], None] = "bd514ccfd36d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medication_logs",
        sa.Column(
            "medication_log_seq", sa.Integer(), autoincrement=True, nullable=False, comment="약 복용 기록 기본키"
        ),
        sa.Column("medication_schedule_seq", sa.Integer(), nullable=False, comment="약 예정 시각 기본키(외래키)"),
        sa.Column("log_date", sa.Date(), nullable=False, comment="복용 기록 날짜"),
        sa.Column(
            "status", sa.Enum("UNCHECKED", "DONE", "SKIPPED", name="checkstatus"), nullable=False, comment="복용 여부"
        ),
        sa.Column("actual_time", sa.Time(), nullable=True, comment="실제 복용 시각"),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="만들어진 날짜"
        ),
        sa.ForeignKeyConstraint(
            ["medication_schedule_seq"],
            ["medication_schedules.medication_schedule_seq"],
        ),
        sa.PrimaryKeyConstraint("medication_log_seq"),
    )
    op.create_table(
        "supplement_logs",
        sa.Column(
            "supplement_log_seq", sa.Integer(), autoincrement=True, nullable=False, comment="영양제 복용 기록 기본키"
        ),
        sa.Column("supplement_schedule_seq", sa.Integer(), nullable=False, comment="영양제 예정 시각 기본키(외래키)"),
        sa.Column("log_date", sa.Date(), nullable=False, comment="복용 기록 날짜"),
        sa.Column(
            "status", sa.Enum("UNCHECKED", "DONE", "SKIPPED", name="checkstatus"), nullable=False, comment="복용 여부"
        ),
        sa.Column("actual_time", sa.Time(), nullable=True, comment="실제 복용 시각"),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="만들어진 날짜"
        ),
        sa.ForeignKeyConstraint(
            ["supplement_schedule_seq"],
            ["supplement_schedules.supplement_schedule_seq"],
        ),
        sa.PrimaryKeyConstraint("supplement_log_seq"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("supplement_logs")
    op.drop_table("medication_logs")
    # ### end Alembic commands ###
