"""supplement_items, supplement_schedules, medication_items, medication_schedules생성

Revision ID: 7455082168ff
Revises: ac0b6529d627
Create Date: 2026-07-22 16:05:04.054942

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7455082168ff"
down_revision: Union[str, Sequence[str], None] = "ac0b6529d627"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medication_items",
        sa.Column("medication_item_seq", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("product_name", sa.String(length=50), nullable=True),
        sa.Column("company_name", sa.String(length=50), nullable=True),
        sa.Column("nutrition_info", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("photo_path", sa.String(length=255), nullable=True),
        sa.Column(
            "timing",
            sa.Enum("EMPTY", "BEFORE", "AFTER", name="eattiming"),
            nullable=False,
        ),
        sa.Column("status", sa.Enum("ING", "PAUSE", "END", name="eatstatus"), nullable=False),
        sa.Column("is_prescription", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("medication_item_seq"),
    )
    op.create_table(
        "supplement_items",
        sa.Column("supplement_item_seq", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("product_name", sa.String(length=50), nullable=True),
        sa.Column("company_name", sa.String(length=50), nullable=True),
        sa.Column("nutrition_info", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("photo_path", sa.String(length=255), nullable=True),
        sa.Column(
            "timing",
            sa.Enum("EMPTY", "BEFORE", "AFTER", name="eattiming"),
            nullable=False,
        ),
        sa.Column("status", sa.Enum("ING", "PAUSE", "END", name="eatstatus"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("supplement_item_seq"),
    )
    op.create_table(
        "medication_schedules",
        sa.Column("medication_schedule_seq", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("medication_item_seq", sa.Integer(), nullable=False),
        sa.Column("scheduled_time", sa.Time(), nullable=False),
        sa.ForeignKeyConstraint(
            ["medication_item_seq"],
            ["medication_items.medication_item_seq"],
        ),
        sa.PrimaryKeyConstraint("medication_schedule_seq"),
    )
    op.create_table(
        "supplement_schedules",
        sa.Column("supplement_schedule_seq", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("supplement_item_seq", sa.Integer(), nullable=False),
        sa.Column("scheduled_time", sa.Time(), nullable=False),
        sa.ForeignKeyConstraint(
            ["supplement_item_seq"],
            ["supplement_items.supplement_item_seq"],
        ),
        sa.PrimaryKeyConstraint("supplement_schedule_seq"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("supplement_schedules")
    op.drop_table("medication_schedules")
    op.drop_table("supplement_items")
    op.drop_table("medication_items")
    # ### end Alembic commands ###
