"""supplement_items, medication_items에 user_seq 외래키 추가

Revision ID: ab205240e1db
Revises: 086fffd17feb
Create Date: 2026-07-22 17:45:59.811701

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab205240e1db"
down_revision: Union[str, Sequence[str], None] = "086fffd17feb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "medication_items", sa.Column("user_seq", sa.Integer(), nullable=False, comment="유저 기본키(외래키)")
    )
    op.create_foreign_key("fk_medication_items_user_seq", "medication_items", "users", ["user_seq"], ["user_seq"])
    op.add_column(
        "supplement_items", sa.Column("user_seq", sa.Integer(), nullable=False, comment="유저 기본키(외래키)")
    )
    op.create_foreign_key("fk_supplement_items_user_seq", "supplement_items", "users", ["user_seq"], ["user_seq"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_supplement_items_user_seq", "supplement_items", type_="foreignkey")
    op.drop_column("supplement_items", "user_seq")
    op.drop_constraint("fk_medication_items_user_seq", "medication_items", type_="foreignkey")
    op.drop_column("medication_items", "user_seq")
    # ### end Alembic commands ###
