"""supplement_logs 스케줄+날짜 유니크 제약 추가

Revision ID: b31ad305bf7d
Revises: c7d06ae379c7
Create Date: 2026-08-10 18:43:11.094373

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b31ad305bf7d"
down_revision: Union[str, Sequence[str], None] = "c7d06ae379c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "medication_logs",
        "status",
        existing_type=mysql.ENUM("UNCHECKED", "DONE", "SKIPPED", collation="utf8mb4_unicode_ci"),
        type_=sa.Enum("DONE", "SKIPPED", name="checkstatus"),
        existing_comment="복용 여부",
        existing_nullable=False,
    )
    op.alter_column(
        "supplement_logs",
        "status",
        existing_type=mysql.ENUM("UNCHECKED", "DONE", "SKIPPED", collation="utf8mb4_unicode_ci"),
        type_=sa.Enum("DONE", "SKIPPED", name="checkstatus"),
        existing_comment="복용 여부",
        existing_nullable=False,
    )
    op.create_unique_constraint(
        "uq_supplement_logs_schedule_log_date", "supplement_logs", ["supplement_schedule_seq", "log_date"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_supplement_logs_schedule_log_date", "supplement_logs", type_="unique")
    op.alter_column(
        "supplement_logs",
        "status",
        existing_type=sa.Enum("DONE", "SKIPPED", name="checkstatus"),
        type_=mysql.ENUM("UNCHECKED", "DONE", "SKIPPED", collation="utf8mb4_unicode_ci"),
        existing_comment="복용 여부",
        existing_nullable=False,
    )
    op.alter_column(
        "medication_logs",
        "status",
        existing_type=sa.Enum("DONE", "SKIPPED", name="checkstatus"),
        type_=mysql.ENUM("UNCHECKED", "DONE", "SKIPPED", collation="utf8mb4_unicode_ci"),
        existing_comment="복용 여부",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
