"""영양제 복용상태 enum 분리(종료 제거)

Revision ID: c7d06ae379c7
Revises: ed37dd444db4
Create Date: 2026-08-05 14:36:54.597967

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7d06ae379c7"
down_revision: Union[str, Sequence[str], None] = "ed37dd444db4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "supplement_items",
        "status",
        existing_type=mysql.ENUM("ING", "PAUSE", "END", charset="utf8mb4", collation="utf8mb4_unicode_ci"),
        type_=sa.Enum("ING", "PAUSE", name="supplementeatstatus"),
        existing_comment="복용 상태",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "supplement_items",
        "status",
        existing_type=sa.Enum("ING", "PAUSE", name="supplementeatstatus"),
        type_=mysql.ENUM("ING", "PAUSE", "END", charset="utf8mb4", collation="utf8mb4_unicode_ci"),
        existing_comment="복용 상태",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
