"""medication FK cascade + logs 유니크 제약 추가

Revision ID: e0ce9a9c641a
Revises: b31ad305bf7d
Create Date: 2026-08-13 14:43:18.794859

"""

from typing import Sequence, Union

from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0ce9a9c641a"
down_revision: Union[str, Sequence[str], None] = "b31ad305bf7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "medication_logs",
        "medication_schedule_seq",
        existing_type=mysql.INTEGER(),
        comment="약 예정 시각 기본키(외래키). 스케줄이 삭제되면 딸린 복용 기록도 함께 삭제됨",
        existing_comment="약 예정 시각 기본키(외래키)",
        existing_nullable=False,
    )
    op.create_unique_constraint(
        "uq_medication_logs_schedule_log_date", "medication_logs", ["medication_schedule_seq", "log_date"]
    )
    op.drop_constraint(op.f("medication_logs_ibfk_1"), "medication_logs", type_="foreignkey")
    op.create_foreign_key(
        "medication_logs_ibfk_1",
        "medication_logs",
        "medication_schedules",
        ["medication_schedule_seq"],
        ["medication_schedule_seq"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "medication_schedules",
        "medication_item_seq",
        existing_type=mysql.INTEGER(),
        comment="약 기본키(외래키). 항목이 삭제되면 딸린 스케줄도 함께 삭제됨",
        existing_comment="약 기본키(외래키)",
        existing_nullable=False,
    )
    op.drop_constraint(op.f("medication_schedules_ibfk_1"), "medication_schedules", type_="foreignkey")
    op.create_foreign_key(
        "medication_schedules_ibfk_1",
        "medication_schedules",
        "medication_items",
        ["medication_item_seq"],
        ["medication_item_seq"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("medication_schedules_ibfk_1", "medication_schedules", type_="foreignkey")
    op.create_foreign_key(
        op.f("medication_schedules_ibfk_1"),
        "medication_schedules",
        "medication_items",
        ["medication_item_seq"],
        ["medication_item_seq"],
    )
    op.alter_column(
        "medication_schedules",
        "medication_item_seq",
        existing_type=mysql.INTEGER(),
        comment="약 기본키(외래키)",
        existing_comment="약 기본키(외래키). 항목이 삭제되면 딸린 스케줄도 함께 삭제됨",
        existing_nullable=False,
    )
    op.drop_constraint("medication_logs_ibfk_1", "medication_logs", type_="foreignkey")
    op.create_foreign_key(
        op.f("medication_logs_ibfk_1"),
        "medication_logs",
        "medication_schedules",
        ["medication_schedule_seq"],
        ["medication_schedule_seq"],
    )
    op.drop_constraint("uq_medication_logs_schedule_log_date", "medication_logs", type_="unique")
    op.alter_column(
        "medication_logs",
        "medication_schedule_seq",
        existing_type=mysql.INTEGER(),
        comment="약 예정 시각 기본키(외래키)",
        existing_comment="약 예정 시각 기본키(외래키). 스케줄이 삭제되면 딸린 복용 기록도 함께 삭제됨",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
