"""영양제 스케줄/복용기록 FK에 ON DELETE CASCADE 추가

Revision ID: ed37dd444db4
Revises: ab205240e1db
Create Date: 2026-08-04 15:41:07.461350

"""

from typing import Sequence, Union

from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed37dd444db4"
down_revision: Union[str, Sequence[str], None] = "ab205240e1db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "supplement_logs",
        "supplement_schedule_seq",
        existing_type=mysql.INTEGER(),
        comment="영양제 예정 시각 기본키(외래키). 스케줄이 삭제되면 딸린 복용 기록도 함께 삭제됨",
        existing_comment="영양제 예정 시각 기본키(외래키)",
        existing_nullable=False,
    )
    op.drop_constraint(op.f("supplement_logs_ibfk_1"), "supplement_logs", type_="foreignkey")
    op.create_foreign_key(
        "supplement_logs_ibfk_1",
        "supplement_logs",
        "supplement_schedules",
        ["supplement_schedule_seq"],
        ["supplement_schedule_seq"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "supplement_schedules",
        "supplement_item_seq",
        existing_type=mysql.INTEGER(),
        comment="영양제 기본키(외래키). 항목이 삭제되면 딸린 스케줄도 함께 삭제됨",
        existing_comment="영양제 기본키(외래키)",
        existing_nullable=False,
    )
    op.drop_constraint(op.f("supplement_schedules_ibfk_1"), "supplement_schedules", type_="foreignkey")
    op.create_foreign_key(
        "supplement_schedules_ibfk_1",
        "supplement_schedules",
        "supplement_items",
        ["supplement_item_seq"],
        ["supplement_item_seq"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("supplement_schedules_ibfk_1", "supplement_schedules", type_="foreignkey")
    op.create_foreign_key(
        op.f("supplement_schedules_ibfk_1"),
        "supplement_schedules",
        "supplement_items",
        ["supplement_item_seq"],
        ["supplement_item_seq"],
    )
    op.alter_column(
        "supplement_schedules",
        "supplement_item_seq",
        existing_type=mysql.INTEGER(),
        comment="영양제 기본키(외래키)",
        existing_comment="영양제 기본키(외래키). 항목이 삭제되면 딸린 스케줄도 함께 삭제됨",
        existing_nullable=False,
    )
    op.drop_constraint("supplement_logs_ibfk_1", "supplement_logs", type_="foreignkey")
    op.create_foreign_key(
        op.f("supplement_logs_ibfk_1"),
        "supplement_logs",
        "supplement_schedules",
        ["supplement_schedule_seq"],
        ["supplement_schedule_seq"],
    )
    op.alter_column(
        "supplement_logs",
        "supplement_schedule_seq",
        existing_type=mysql.INTEGER(),
        comment="영양제 예정 시각 기본키(외래키)",
        existing_comment="영양제 예정 시각 기본키(외래키). 스케줄이 삭제되면 딸린 복용 기록도 함께 삭제됨",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
